module.exports = {
    rouge: "Red",
    bleu: "Blue",
    vert: 'Green',
    violet: 'Purple',
    jaune: 'Yellow',
    noir: 'Black',
    blanc: 'White',
    gris: 'Grey',
    rose: 'LuminousVividPink',
    orange: 'Orange',
    red: 'Red',
    blue: 'Blue',
    green: 'Green',
    purple: 'Purple',
    yellow: 'Yellow',
    black: 'Black',
    white: 'White',
    grey: 'Grey',
    pink: 'LuminousVividPink',
    luminous_vivid_pink: 'LuminousVividPink',
    luminousvividpink: 'LuminousVividPink',
    blurple: 'Blurple'
}